### ISSUE TITLE
[BUG] Object Reference Not Defined

### ISSUE THREAD

**Issue by Adrthegamedev** [DesktopGooseUnofficial/launcher#108]
**Describe the bug**
An object reference not defined error.

**To Reproduce**
1. Make a folder in Mods named after anything that's not in the backend
2. Launch the Launcher

**Expected behavior**
...the object reference to be defined?

**Screenshots**
![error](https://user-images.githubusercontent.com/46429482/77401283-99987580-6de7-11ea-80e8-232cdb4049a7.png)
[error.txt](https://github.com/DesktopGooseUnofficial/launcher/files/4373840/error.txt)

**Desktop (please complete the following information):**
 - Windows 10
 - Version 2.0 (BETA 1)

**Comment by VukAnd** [comment]
> put Launcher in goose folder
Does this fix itself if you *don't* put the Launcher in the goose folder and put it somewhere else?

**Comment by Adrthegamedev** [comment]
Nope, still happens

**Comment by 1JQ** [comment]
Can you send everything from details, please?

**Comment by 1JQ** [comment]
[ResourceHubLauncher.zip](https://github.com/DesktopGooseUnofficial/launcher/files/4374951/ResourceHubLauncher.zip)

Try new version, and change in %localappdata%/ResourceHub Launcher/config.json devmode to true (and save) (do that before testing if it works) and them send console output

**Comment by VukAnd** [comment]
I have just managed to repro this by making a mod folder named after anything not in the backend. Reason for this seems to be this uncatched line:

![image](https://user-images.githubusercontent.com/46850780/77517707-e11d1100-6e7c-11ea-9d82-0acd0e952015.png)

**Comment by VukAnd** [comment]
#111 fixes this... somewhat - the error shows up if you click on a mod not in the backend now.

**Comment by VukAnd** [comment]
Now resolved.
