### ISSUE TITLE
[BUG] Close Button doesn't appear

### ISSUE THREAD

**Issue by CodeF53** [DesktopGooseUnofficial/launcher#116]
![image](https://user-images.githubusercontent.com/37855219/77663342-949c0900-6f42-11ea-9a67-f599d6a383b0.png)

*edited by @VukAnd to remove feature request related data since this is a bug, the close button should show up*

**Comment by VukAnd** [comment]
uuuh this is a strange one, it shows up for me.

**Comment by Wuzado** [comment]
It shows up for me though. Can you specify your setup or any ways to reproduce it? Also, I assume you're running the newest Beta build?

**Comment by CodeF53** [comment]
I am running the latest beta, with latest windows 10, and latest Nvidia
drivers.

My relevant specs are as follows:
GeForce Gtx 1080 ti
Intel i7 6700k

**Comment by LilSizzurp** [comment]
Haven't had this issue.
Could you provide steps to reproduce it?

// Closing issue until I can validate it.
