### ISSUE TITLE
[BUG] Dark theme boot issue...

### ISSUE THREAD

**Issue by CodeF53** [DesktopGooseUnofficial/launcher#117]
**Describe the bug**
On launching the.. launcher, I get flashbanged by the Mod selector
![image](https://user-images.githubusercontent.com/37855219/77663573-d1680000-6f42-11ea-9036-4be832fdc214.png)

**To Reproduce**
1. Open the launcher

**PC:**
 - OS: [e.g. Windows 10]
 - Launcher version [e.g. 2.0 Beta]
 - Dark mode in windows enabled

**Additional context**
This was a fresh install of launcher 2.0

**Comment by 1JQ** [comment]
We can't really do nothing about that #NetSucksAtGraphics (maybe in future we will try to fix that, but fixing this will not be easy)
