### ISSUE TITLE
[FEATURE] mod disabling

### ISSUE THREAD

**Issue by Plutonium-236** [DesktopGooseUnofficial/launcher#121]
there is a little problem, sometimes, when messing  around i need to disable a mod, but that dosent exist

so i came up with this absurd code:
` 
public static bool disableMod(String path) {
            try {
                if (File.Exists(path))  {

                    File.Move(path, Path.Combine(Path.GetDirectoryName(path), Path.GetFileNameWithoutExtension(path) + ".nl"));
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception e)
            {
                return false;
            }

        }
`
you could uninstall but that takes to much time

**Comment by VukAnd** [comment]
haha funny thing is, mod disabling is already in 2.0

**Comment by Plutonium-236** [comment]
wait how is it used

**Comment by 1JQ** [comment]
Right click installed mod
