### ISSUE TITLE
[REQUEST] Add an obvious button to get out of launcher settings

### ISSUE THREAD

**Issue by GenericApe** [DesktopGooseUnofficial/launcher#124]
So when I went into the Resource Hub Settings, it took me a while to figure out how to exit the page. My solution is to have a clear, concise button labelled "Exit Settings" so it will be more obvious to inexperienced people like me.

An alternative would be to have "esc" as the exit button. This would still be more obvious since most programs use "esc" as a way to exit something.

**Comment by LilSizzurp** [comment]
Added in 3e739f7.
