### ISSUE TITLE
[BUG] The scrollbar part is broken.

### ISSUE THREAD

**Issue by 03172008** [DesktopGooseUnofficial/launcher#129]
[Bug description]
Whenever I open the launcher, it will give this alert: 

![e791bd384a4e56b0045ca32ccb04b1f5](https://user-images.githubusercontent.com/47307733/84663957-d60dd600-aeeb-11ea-98cd-cf2cac8a66a2.png) 

and if I press continue, this is what I see: 

![image](https://user-images.githubusercontent.com/47307733/84664229-3a309a00-aeec-11ea-8b2e-992e43bcd282.png)

=========================================================

1. Follow the directions to install OnePunchGoose on https://desktopgooseunofficial.github.io/ResourceHub/mods/OnePunchGoose.html 

2. Open Launcher

3. See error

4. Press continue

5. See rendering error

=========================================================
[What should've happened]
I expected it to open normally, and have the OnePunchGoose mod enabled, But instead, these things happened.

[Screenshots]
![e791bd384a4e56b0045ca32ccb04b1f5](https://user-images.githubusercontent.com/47307733/84663957-d60dd600-aeeb-11ea-98cd-cf2cac8a66a2.png)
![image](https://user-images.githubusercontent.com/47307733/84664229-3a309a00-aeec-11ea-8b2e-992e43bcd282.png)

=========================================================

[Desktop]
 - OS: Windows 10 Pro
 - Launcher version 2.0 [BETA]

=========================================================

[Context]
I had just installed the OnePunchGoose Mod.

**Comment by 03172008** [comment]
I may have fixed the rendering issue by restarting the launcher after turning on beta mode under auto-update in settings and allowing "Unsafe" Mods.

**Comment by 03172008** [comment]
If this was never an issue, this ^ solution fixes it, and it was just a mistake on my side, Please close this thread. I do not want to close this thread accidentally if it was an actual issue.

**Comment by 03172008** [comment]
![image](https://user-images.githubusercontent.com/47307733/84665377-c42d3280-aeed-11ea-8d71-1bea9830256f.png)
  


^ This is what I see now after making the changes detailed above

**Comment by 03172008** [comment]
Wait nevermind the issue came back again.

**Comment by LilSizzurp** [comment]
You know it'd be helpful if you clicked "Details" or provided the stack trace.

**Comment by LilSizzurp** [comment]
I'm gonna try to recreate it.
If I find any issues I'll notify you.

**Comment by LilSizzurp** [comment]
This was fixed alongside #117 in https://github.com/DesktopGooseUnofficial/launcher/commit/3e739f7ceb7cc2581aad8d1b30dbccc345c6f42b
Release will be pushed soon.
// Issue closed. Please contact me if the issue is still happening.
