### ISSUE TITLE
[BUG] Internet Not Connected problem

### ISSUE THREAD

**Issue by windows10win7posreadywoeskio** [DesktopGooseUnofficial/launcher#132]
**Describe the bug**
When I open the launcher it says a kind of error like this:
"Hmm... It doesn't look like you have any internet connection. The ResourceHub launcher cannot function properly without any internet connection. Please try again when you do get an internet connection though!"

I still have an internet connection.

**To Reproduce**
1. Go to 'Downloads'
2. Double-Click on 'ResourceHubLauncher.exe'
3. See error

**Expected behavior**
When I clicked on ResourceHubLauncher.exe, I was expecting it to work. Instead, it showed the error.

**Screenshots**
If applicable, add screenshots to help explain your problem. [e.g. a video or GIF of you reproducing the error]
![image](https://user-images.githubusercontent.com/56192384/89095043-2dacc600-d3f4-11ea-956f-cb2c8a33fcc6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Launcher version: 2.0 BETA 1

**Additional context**

**Comment by Vukky123** [comment]
This currently happens because the Launcher uses http://rhl.my.to to check if an internet connection is available, but rhl.my.to has been down for a while. A fix is already ready and will be launched in 2.0 BETA 2 hopefully.
