### ISSUE TITLE
[BUG] .net connection issues

### ISSUE THREAD

**Issue by mobilegmYT** [DesktopGooseUnofficial/launcher#135]
**Describe the bug**
I get this error when launching the beta hub.
`Server returned a 404 error
************** Exception Text **************
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)`

**To Reproduce**
Steps to reproduce the behaviour:
1. Download and launch the beta hub.

**Expected behaviour**
The hub opens without issue

**Screenshots**
![image](https://user-images.githubusercontent.com/44128563/91643250-b6685300-e9ee-11ea-9eeb-22bd57189ffa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Launcher version 2.0 (BETA 1)

**Comment by Vukky123** [comment]
Same cause as #132.
