### ISSUE TITLE
Fix issue where some mods don't run properly in the launcher, but works fine when running manually

### ISSUE THREAD

**Issue by VukAnd** [DesktopGooseUnofficial/launcher#31]
(pretty sure this is the Mod is for older version error)

**Comment by 1JQ** [comment]
If you mean: "Mod is for older version" I can't fix it in shaggy's mods

**Comment by 1JQ** [comment]
Without Shaggy

**Comment by 1JQ** [comment]
(will be fixed after 2.0 comes out)

**Comment by 1JQ** [comment]
This error only happens when using some mods together
