### ISSUE TITLE
Automatic Launcher Update

### ISSUE THREAD

**Issue by 1JQ** [DesktopGooseUnofficial/launcher#32]
Automatic updater for the launcher, instead of asking user (like Discord does)

**Comment by VukAnd** [comment]
yes it would be very fun to see it update on developer builds making developer builds impossible to test

**Comment by 1JQ** [comment]
Y E S

**Comment by 1JQ** [comment]
just make the check for developer version

**Comment by 1JQ** [comment]
or lock update when bool is active

**Comment by VukAnd** [comment]
I feel like auto-update should be optional, and what we have now is the default

**Comment by 1JQ** [comment]
Just make enabled by default and possibily to disable auto update in settings

**Comment by 1JQ** [comment]
I've not seen any app with auto update disabled by default

**Comment by VukAnd** [comment]
Maybe ask on first time boot if the user wants to enable auto update?

**Comment by 1JQ** [comment]
You've said a while ago that you don't want to make to many popups

**Comment by VukAnd** [comment]
hmm, that's true, enabled by default and toggle in setting could work then, as long as it doesn't auto-update on the first run (since it makes no sense to do so)

**Comment by 1JQ** [comment]
Will not happend when latest version was downloaded

**Comment by VukAnd** [comment]
(what about developer builds though? devmode check?)

**Comment by 1JQ** [comment]
Yes (I've talked about this before)
