### ISSUE TITLE
Mods don't work

### ISSUE THREAD

**Issue by EliteAspect21** [DesktopGooseUnofficial/launcher#44]
I installed the ResourceHub Launcher and installed a few mods. I made sure the mods were in the mods folder. They won't work, regardless if I start it from the GooseDesktop.exe program, or from the launcher. Is there any other steps I need to follow?

**Comment by VukAnd** [comment]
Does your config.ini file have `EnableMods` set to True?

**Comment by 1JQ** [comment]
Are you sure you have mods option in config active? (Every time when goose is activated should warming popup)

**Comment by EliteAspect21** [comment]
It says EnableMods=True

**Comment by VukAnd** [comment]
Were those mods ZIP files? If so, can you comment with one of the folders of those mods? (you can use ctrl+v or attach files)

**Comment by EliteAspect21** [comment]
Nope, I unzipped all of them.

**Comment by VukAnd** [comment]
Yeah, but what does one of your unzipped folders look like?

**Comment by EliteAspect21** [comment]
Ah, I found out why it wasn't working. I just needed to restart my PC

**Comment by VukAnd** [comment]
Well then, nice to see you got it resolved though.
