### ISSUE TITLE
[BUG] Cannot find update.exe (on nightly build v2)

### ISSUE THREAD

**Issue by NBN-Alex** [DesktopGooseUnofficial/launcher#89]
**Describe the bug**
On opening the file `ResourceHubLauncher.exe`, the user is presenting with an error that update.exe cannot be found. (and the link to download is at \*\*insert link here\*\*. Pressing close will close the app without an error code.

**To Reproduce**
1. Download RHL from https://github.com/DesktopGooseUnofficial/launcher-nightly/releases/tag/nightly-1
2. Double-click on the launcher
(Tried also moving the file to the desktop goose folder tha tI've named C:\Goose\)

**Expected behavior**
RHL to open to the main screen, or at least provide the error and then continue to the main launch screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/15615282/76727668-df7f7a80-6711-11ea-80f0-8f329e383696.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro x64
 - Launcher version: v2.0.0 (nightly)

**Comment by 1JQ** [comment]
This is not a bug, this is a way to lock off distributing launcher without Updater. Just disable auto update in (%localappdata%/ResourceHub Launcher/config.json) config and app will ignore that you don't have Updater

**Comment by NBN-Alex** [comment]
Would it help to have a "this is a nightly/unstable build" warning as the first screen instead that can be disabled/removed on full releases? I only found out about this problem after someone else reported the same issue in the #goose-support discord channel and tested it myself.  It seems like they managed to download the nightly build without knowing and just assumed it was their PC that was broken.

It would be a better UX practice to place the warning ahead of the user (ie, "you're on the wrong build, this one is meant for testing") instead of making what's more of a secret code to get the build working. :)

**Comment by 1JQ** [comment]
Thanks for the suggestion. I added warming right now.
